server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'user'
    url: jdbc:postgresql://localhost:5440/customer
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0