server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'user'
    password: 'password'
    url: jdbc:postgresql://localhost:5441/postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka